version: "3.9"
services:
  docker-mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: insurance
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 20s
      timeout: 60s
      retries: 3

  insurance-api:
    image: insurance-api-image
    expose:
    - "8090"
    build: .
    container_name: insurance-api
    restart: on-failure
    depends_on:
      docker-mysql:
        condition: service_healthy
    ports:
      - "8090:8090"